config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Siel::Application.routes.draw do
  patch 'casos_verificacion/:id/firmar', to: 'casos_verificacion#firmar'
  patch 'casos_verificacion/:id/no_firmar', to: 'casos_verificacion#no_firmar'
  patch 'casos_verificacion/:id/borrar_datos', to: 'casos_verificacion#borrar_datos'

  # resources :verificaciones_firmas do
  #   resources :casos_verificacion
  #   patch :actualizar, on: :collection
  # end

  resources :usuarios do
    get :fuerza, on: :member
    get :find_by_email, on: :collection
    put :blanqueo_clave, on: :member
  end

  get 'usuario/cambiar_contrasenia', to: 'usuarios#cambiar_contrasenia'
  post 'usuario/cambiar_contrasenia', to: 'usuarios#cambiar_contrasenia'

  resources :archivos

  get 'archivos/descargar/:id', to: 'archivos#descargar'

  resources :renglones_padron
  resources :archivo_personas
  resources :archivo_lista_cargos
  resources :cargos

  resources :afiliaciones do
    delete :borrar_afiliaciones, on: :collection
  end

  resources :fiscales do
    delete :destroy_new, on: :member
    delete :borrar_fiscales, on: :collection
    post   :importar_fiscales, on: :collection
    get    :archivo_errores, on: :collection
    get    :exportar, on: :collection
    get    :establecimientos_por_comuna, on: :collection
    get    :cantidad_mesas_establecimiento, on: :collection
  end

  resources :personas do
    get :candidaturas, on: :member
    get :archivos_persona, on: :member
    get :busqueda_persona, on: :collection
    get :busqueda_persona_fiscal, on: :collection
    get :limpiar_formulario, on: :collection
    put :cargar_avatar, on: :collection
    get :ver_adjuntos, on: :member
    get :calcular_comuna, on: :collection
  end

  resources :mesa_extranjeros do
    post :importar_mesas_extranjeros, on: :collection
  end

  resources :importacion_escrutinios, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :calcular_resultados
      get  :reparto_cargos
      post :generar_lista_eleccion_general
      get  :imprimir_reparto_cargos
    end

    collection do
      get :estado_importacion_archivo
    end
  end

  # TODO: ver si hay que borrar, los documento se suben por el controller ArchivoPersonas
  post 'personas/adjuntar_documento', to: 'personas#adjuntar_documento'
  get 'personas/descargar_documento/:archivo_persona_id', to: 'personas#descargar_documento'

  resources :padrones do
    get :renglones_importados, on: :member
  end
  get 'padrones/importar/:index', to: 'padrones#importar'

  resources :candidaturas do
    post :renunciar, on: :member
    get  :cumple_ley_cupos, on: :member
    get  :cumple_minimo, on: :member
    get  :eventos, on: :collection
    post :sugerir_orden, on: :collection
    post :aceptar_correccion_cupo, on: :collection
    post :buscar_por_documento, on: :collection
    put  :aplicar_validaciones, on: :collection
    post :cambiar_orden, on: :collection
  end
  get 'candidaturas/importar/lista', to: 'candidaturas#importar_lista'
  post 'candidaturas/procesar_archivo', to: 'candidaturas#procesar_archivo'
  post 'candidaturas/auto_ordenamiento', to: 'candidaturas#auto_ordenamiento'
  post 'candidaturas/deshacer_ordenamiento', to: 'candidaturas#deshacer_ordenamiento'
  post 'candidaturas/subir', to: 'candidaturas#subir'
  post 'candidaturas/bajar', to: 'candidaturas#bajar'
  post 'candidaturas/filtrar'
  post 'candidaturas/oficializar_lista'
  post 'candidaturas/desoficializar_lista'

  get 'expedientes/buscar'

  resources :fuerzas do
    resources :infracciones
    get    :candidaturas, on: :member
    get    :apoderados, on: :member
    get    :agregar_apoderado, on: :collection
    post   :listado_apoderados, on: :collection
    get    :select_fuerzas, on: :collection
    patch  :editar_escudo
    delete :eliminar_escudo

    member do
      delete :baja
    end
  end

  resources :fuerza_eleccion, only: [:update]

  post 'fuerzas/filtrar'

  resources :elecciones do
    get 'descargar_resolucion'
    get :fuerzas, on: :member
    get :cargos, on: :member
    get :exportar_apoderados, on: :member
    get :actual, on: :collection

    post   :cargar_reparto, on: :member
    post   :grabar_reparto, on: :member
    delete :destroy_reparto, on: :member
    get    :reparto_anexo_1, on: :member
    get    :reparto_anexo_2, on: :member
    get    :reparto_anexo_2_2009, on: :member
    get    :reparto_anexo_3_2009, on: :member
    get    :reparto_anexo_4_2009, on: :member
    get    :reparto_anexo_5_2009, on: :member
  end
  post 'elecciones/filtrar'

  resources :eleccion_cargos
  resources :incidencias do
    delete :borrar_incidencias, on: :collection
  end

  resources :listas do
    resources :lista_cargos do
      member do
        post :borrar_candidaturas
        post :borrar_adhesiones
        post :importar_personas
        get  :estado_importacion_archivo
        get  :descargar_archivo_errores_importacion
        post :validar
        post :cerrar_lista
        post :abrir_lista
        get  :imprimir_candidaturas
        get  :exportar_adhesiones
        get  :descargar_exportacion_adhesiones
        get  :imprimir_auto_ordenamiento
        get  :versiones
        get  :exportar_versiones
        get  :descargar_exportacion_versiones
        get  :observaciones
      end
    end

    member do
      post :validar
      post :oficializar
      post :desoficializar
      get  :imprimir_lista_prototipo
      get  :imprimir_acta_presentacion
      get  :bitacora
      put  :asignar_numero_escrutinio
    end

    collection do
      get :seccion_cargos_habilitados
      get :imprimir_resolucion_oficializacion
      get :imprimir_comunicado_articulo_26
    end
  end

  resources :listas_generales do
    resources :lista_cargos_generales do
      member do
        get  :imprimir_lista_general
      end
    end
  end

  resources :observaciones, only: [:index, :edit, :update] do
    collection do
      post :subsanar
    end
  end

  resources :adhesiones, only: [:index, :create, :destroy]
  resources :configuraciones, only: [:show, :update]
  resources :siel_archivos
  resources :registro_candidaturas do
    delete :borrar_registros_candidaturas, on: :collection
  end

  resources :calles, only: [:index]

  resources :antecedentes_penales do
    member do
      post :enviar_solicitud
      get :descargar_antecedente_penal_pdf
    end
  end

  root to: 'root#index'

  # Rutas del controller admin
  post 'admin/login'
  post 'admin/login_extranet'
  get  'admin/login'
  get  'admin/logout'

  mount Sidekiq::Web => '/sidekiq'
end

app/helpers/candidaturas_helper.rb
module CandidaturasHelper

  def letra_sexo(persona)
    if persona.present? && persona.sexo.present?
      persona.sexo.capitalize
    else
      '-'
    end
  end

  def leyenda(candidatura)
    if !candidatura.figura_en_padron? and !candidatura.persona.nativo_caba?
      "<br/><strong><small class='rojo'>No es nativo CABA y no figura en padrón</small></strong>".html_safe
    end
  end

  def atributos_tr_armado_lista(candidatura)
    css_class = ''
    title = ''

    if candidatura.persona.candidaturas_multiples(candidatura.eleccion).count > 1
      css_class << 'warning '
      title << 'Esta persona posee más de una candidatura en esta elección'
    end

    if !candidatura.figura_en_padron? && !candidatura.persona.nativo_caba?
      css_class << 'linea_destacada'
    end

    "class='#{css_class}' title='#{title}'".html_safe
  end

  def descripcion_cargo(candidatura)
    descripcion = candidatura.cargo.nombre

    unless candidatura.cargo.nombre == Cargo::CARGOS[:jefe] or candidatura.cargo.nombre == Cargo::CARGOS[:vicejefe]
      descripcion += (candidatura.titular? ? ' Titular' : ' Suplente')
    end

    descripcion
  end

  def cambios_significativos(cambios)
    cambios.select do |k, v|
      k != 'domicilio_id' && !(v[0].nil? && v[1] == false)
    end
  end

  def orden(candidatura)
    if candidatura.cargo.nombre == Cargo::CARGOS[:diputado]
      if !candidatura.titular?
        candidatura.orden - candidatura.cargo.cantidad_minima
      else
        candidatura.orden
      end
    else
      candidatura.orden
    end
  end

  def css_class_sugerido(original, sugerida, incorregible)
    if !incorregible.nil? && sugerida.orden >= incorregible.orden
      'error'
    elsif original.persona != sugerida.persona
      'success'
    else
      ''
    end
  end

  def css_class_estado(candidatura)
    if candidatura.valida?
      if candidatura.documentacion_completa?
        'btn-success'
      else
        'btn-warning'
      end
    else
      'btn-danger'
    end
  end

  def icono_estado(candidatura)
    if candidatura.valida?
      if candidatura.documentacion_completa?
        'icon-thumbs-up'
      else
        'icon-eye-open'
      end
    else
      'icon-thumbs-down'
    end
  end

  def lista_oficializada(fuerza, eleccion)
    !fuerza.nil? and !eleccion.nil? and fuerza.oficializada?(eleccion)
  end

  def opciones_booleanas
    { '' => nil, 'Si' => true, 'No' => false }
  end

end

app/views/candidaturas/_agregar_candidatura.html.erb
<% unless lista_oficializada(fuerza, eleccion) %>
	<%= form_tag({action: :agregar_candidatura}, {remote: true, id: 'form_agregar_candidatura'}) do %>
		<%= hidden_field_tag :eleccion_id %>
		<%= hidden_field_tag :fuerza_id %>
		<tr>
			<td width="5%">-</td>
			<td width="8%"><%= select_tag :cargo_id, options_from_collection_for_select(cargos, :id, :nombre), class: 'form-control' %></td>
			<td width="12%"><%= number_field_tag :numero_documento, nil, class: 'form-control', placeholder: 'DNI' %></td>
			<td width="19%"><%= text_field_tag :nombres, nil, class: 'form-control', placeholder: 'Nombres' %></td>
			<td width="19%"><%= text_field_tag :apellidos, nil, class: 'form-control', placeholder: 'Apellidos' %></td>
			<td widht="8%"><%= select_tag :sexo, options_for_select([['Femenino', 'F'], ['Masculino', 'M']]), class: 'form-control' %></td>
			<td width="25%" colspan="3" nowrap>
				<%= link_to "<i class='glyphicon glyphicon-plus'></i> Agregar".html_safe, '#', class: 'btn btn-default', id: 'link_agregar_candidatura' %>
			</td>
		</tr>
	<% end %>
<% end %>

app/views/candidaturas/_bitacora_cambios.html.erb
<div class="row">
	<div class="col-md-12">

		<table class="table table-bordered table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th>Fecha</th>
					<th>DNI</th>
					<th>Apellidos y Nombres</th>
					<th>Cambio Realizado</th>
					<th>Responsable</th>
				</tr>
			</thead>
			<tbody>
				<% versiones.each do |v| %>
					<% object = v.reify %>
					<tr>
						<td><%= l(v.created_at.to_date) %></td>
						<% if object.kind_of?(Candidatura) %>
							<td><%= object.persona.numero_documento %></td>
							<td><%= object.persona.apellidos %>, <%= object.persona.nombres %></td>
						<% elsif object.kind_of?(Persona) %>
							<td><%= object.numero_documento %></td>
							<td><%= object.apellidos %>, <%= object.nombres %></td>
						<% end %>
						<td>
							<% if v.event == 'destroy' %>
								<strong>- BORRADA -</strong>
								<%= leyenda(object) %>
							<% else %>
								<% cambios_significativos(v.changeset).each do |k, v| %>								
									<strong><%= t(k) %></strong>: Cambi&oacute; de 
									<%= (k == 'orden') ? orden(object) : valor_cambio_version(v[0]) %> a 
									<%= (k == 'orden') ? orden(object.next_version) : valor_cambio_version(v[1]) %>.<br/>
								<% end %>
							<% end %>
						</td>
						<td><%= v.whodunnit %></td>
					</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>

app/views/candidaturas/_candidatura.html.erb
<tr>
	<td><%= number_with_delimiter(candidatura.persona_numero_documento, delimiter: '.') %></td>
	<td><%= candidatura.persona_nombres %> <%= candidatura.persona_apellidos %></td>
	<td><%= descripcion_cargo(candidatura) %></td>
	<td><%= candidatura.persona_sexo %></td>
	<td><%= candidatura.fuerza_nombre %></td>
	<td><%= candidatura.eleccion_fecha.year %></td>
	<td>
		<%= link_to "<i class='#{icono_estado(candidatura)}'></i>".html_safe, edit_candidatura_path(candidatura), class: "btn #{css_class_estado(candidatura)}" %>
		<%= link_to "<i class='glyphicon glyphicon-pencil'></i> Detalle".html_safe, edit_persona_path(candidatura.persona), class: 'btn btn-default' %>
	</td>
</tr>

app/views/candidaturas/agregar_candidatura.js.erb
$('#tabla_diputados').html('<%= escape_javascript(mensaje_cupos(@diputados)) %><%= escape_javascript(render(partial: 'tabla_candidaturas', locals: { candidaturas: @diputados })) %>');
$('#tabla_jefaturas').html('<%= escape_javascript(render(partial: 'tabla_candidaturas', locals: { candidaturas: @jefaturas })) %>');
$('#tabla_comuneros').html('<%= escape_javascript(render(partial: 'tabla_candidaturas', locals: { candidaturas: @comuneros })) %>');

$('#form_agregar_candidatura')[0].reset();

<% if @ya_existe_persona %>
	pop_info('La persona con número de documento <%= params[:numero_documento] %> ya figuraba en la base. Se tomó la información de la base y no la ingresada manualmente.');
<% end %>

<% unless flash[:warning].nil? or flash[:warning].empty? %>
	pop_info('<%= flash[:warning] %>');
<% end %>

$('#botonera_candidaturas').html('<%= escape_javascript(render(partial: "botonera_candidaturas", locals: { fuerza: @fuerza, eleccion: @eleccion })) %>');

app/views/candidaturas/edit.html.erb
<div class="row">
	<h2>Validaciones de Candidatura</h2>
	<hr/>

	<%= render "shared/error_messages", :target => @candidatura %>

</div>

<div class="row">
	<% if @renglon.nil?  %>

		<div class="alert alert-danger">
			<strong>Atenci&oacute;n</strong>
			<p>No se ha encontrado ning&uacute;n registro del padr&oacute;n con matr&iacute;cula <%= @candidatura.persona.numero_documento %>.</p>
		</div> 

	<% else	%>
			
		<table class="table table-bordered">
			<caption>Informaci&oacute;n del Padr&oacute;n</caption>
			<thead>
				<tr>
					<th>Apellido</th>
					<th>Nombre</th>
					<th>Clase</th>
					<th>Profesi&oacute;n</th>
					<th>Domicilio</th>
					<th>Analfabeto</th>
					<th>Tipo Documento</th>
					<th>Secci&oacute;n</th>
					<th>Circuito</th>
					<th>Mesa</th>
					<th>Sexo</th>
					<th>Matr&iacute;cula</th>
				</tr>											
			</thead>		
			<tbody>
				<tr>
					<td><%=@renglon.apellido%></td>
					<td><%=@renglon.nombre%></td>
					<td><%=@renglon.clase%></td>
					<td><%=@renglon.profesion%></td>
					<td><%=@renglon.domicilio%></td>
					<td><%=@renglon.analfabeto%></td>
					<td><%=@renglon.tipo_documento%></td>
					<td><%=@renglon.seccion%></td>
					<td><%=@renglon.circuito%></td>
					<td><%=@renglon.mesa%></td>
					<td><%=@renglon.sexo%></td>
					<td><%=@renglon.matricula%></td>
				</tr>
			</tbody>
		</table>	
	<% end %>
</div>

<div class="row">

	<div class="col-md-4 well">
		<dl class="dl-horizontal">
			<dt>Elecci&oacute;n:</dt>
			<dd><%=@candidatura.eleccion_cargo.eleccion.descripcion %></dd>
			<dt>Cargo:</dt>
			<dd><%=@candidatura.eleccion_cargo.cargo.nombre %></dd>
			<dt>Orden:</dt>
			<dd><%= orden(@candidatura) %></dd>
		</dl>
		<dl class="dl-horizontal">
			<dt>Apellidos:</dt>
			<dd><%= best_in_place @candidatura.persona, :apellidos %></dd>
			<dt>Nombres:</dt>
			<dd><%= best_in_place @candidatura.persona, :nombres %></dd>
			<dt>Domicilio:</dt>
			<dd><%=@candidatura.persona.domicilio.descripcion unless @candidatura.persona.domicilio.nil? %>&nbsp;</dd>
			<dt>Sexo:</dt>
			<dd><%= sexo(@candidatura.persona.sexo).capitalize %></dd>
			<dt>N&uacute;mero Documento:</dt>
			<dd><%= best_in_place @candidatura.persona, :numero_documento %></dd>
			<dt>Lugar de Nacimiento:</dt>
			<dd><%= best_in_place @candidatura.persona, :lugar_nacimiento, inner_class: 'form-control' %></dd>
			<dt>Fecha de Nacimiento:</dt>
			<dd><%= best_in_place @candidatura.persona, :fecha_nacimiento, display_with: 'l', inner_class: 'form-control', html_attrs: {placeholder: 'DD/MM/YYYY'} %></dd>
		</dl>
	</div>

	<%= form_for(@candidatura, html:{id: 'form_validaciones'}) do |f| %>

		<div class="col-md-8 well">

			<div class="row">
					<div class="col-md-5">
					<dl class="dl-horizontal">
						<dt>Argentino</dt>
						<dd>
							<% Candidatura::TIPOS_NACIONALIDAD.each do |tn| %>
										<label class="radio">
											<%= f.radio_button :tipo_nacionalidad, tn, onclick: "cambio_nacionalidad('#{tn}');" %> <%= tipo_nacionalidad(tn) %>
										</label>			      
							<% end %>
						</dd>
					</dl>
				</div>
				<div class="col-md-6">
						<div>
								<label class="checkbox">
									<%= f.check_box 'edad_valida?', disabled: true %> <%= etiqueta_edad_valida(@candidatura.eleccion_cargo.cargo) %>
								</label>			      
						</div>
					<br/>
				
					<% if @candidatura.eleccion_cargo.cargo.nombre == Cargo::CARGOS[:comunero] %>
						<div>
							<label class="checkbox">					
								<%= f.check_box 'reside_en_comuna?', id: 'reside_en_comuna' %> Residencia en comuna
							</label>			      
						</div>
					<% else %>				 			
						<div>
							<%= f.fields_for(:persona) do |fp| %>
								<label class="checkbox">
									<%= fp.check_box 'nativo_caba?', id: 'nativo_caba', disabled: (f.object.nativo? || f.object.tipo_nacionalidad.nil? ? nil: 'disabled') %> Es nativo C.A.B.A.								
								</label>			      
							<% end %>
						</div>
					<% end %>			  
						<div>
							<label class="checkbox" id="label_constancia_domicilio">
								<%= f.check_box 'constancia_domicilio?', id: 'constancia_domicilio' %> 
								<span class="badge badge-warning"><strong><%= Candidatura::VALIDACIONES[:constancia_domicilio] %></strong> </span><br/>
								(<em>debe ser mayor a 4 a&ntilde;os</em>)
							</label>			      
						</div>
						<br/>

						<div>
								<label class="checkbox">
									<%= f.check_box 'fotocopia_dni?' %> <%= Candidatura::VALIDACIONES[:fotocopia_dni] %>
								</label>			      
						</div>
						<div>
								<label class="checkbox">
									<%= f.check_box 'dni_tarjeta?' %> <%= Candidatura::VALIDACIONES[:dni_tarjeta] %>
								</label>			      
						</div>
						<div>
						<label class="checkbox">
									<%= f.check_box 'aceptacion_firmada?' %> <%= Candidatura::VALIDACIONES[:aceptacion_firmada] %>
								</label>			      
						</div>
						<br/>
						
						<div>
								<label class="checkbox text-danger">
									<%= f.check_box 'cargo_dos_periodos?' %> <%= Candidatura::VALIDACIONES[:cargo_dos_periodos] %>
								</label>			      
					</div>
						<div>
								<label class="checkbox text-danger">
									<%= f.check_box 'deudor_alimentario?' %> <%= Candidatura::VALIDACIONES[:deudor_alimentario] %>
								</label>			      
						</div>
						<div>
						<label class="checkbox text-danger">
									<%= f.check_box 'inhabilitado?' %> <%= Candidatura::VALIDACIONES[:inhabilitado] %>
								</label>			      
						</div>
					</div>
			</div>
		</div>

	<% end %>

</div>

<div class="row">
	<%= link_to "<i class='glyphicon glyphicon-ok'></i> Grabar".html_safe, "#", class: "btn btn-primary", id: 'link_grabar_validaciones' %>
	<%= link_to "<i class='glyphicon glyphicon-pencil'></i> Detalle del Candidato".html_safe, edit_persona_path(@candidatura.persona), class: 'btn btn-info' %>
	<%= back_button %>	
</div>

app/views/candidaturas/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Consulta de Candidaturas</h2>
    <hr/>
  </div>
</div>
<div class="row well">

  <%= form_tag(candidaturas_path, method: :get, class: "form-horizontal candidaturas-form", id: 'form_search_candidaturas') do %>

    <div class="col-lg-3 col-md-12">
      <div class="form-group">
        <label class="control-label">Elecci&oacute;n</label>
        <div class="controls">
          <%= select :filtro, :eleccion, options_for_select(@elecciones.map { |e| e.nil? ? [nil, nil]: [e.descripcion, e.id] }, params[:filtro].try(:[], :eleccion)), {}, { id: 'eleccion_id', class: 'form-control' } %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label">Persona</label>
        <div class="controls">
          <div class="input-group col-xs-12 col-md-12 col-lg-12">
            <span class="input-group-addon">DNI</span><%= text_field_tag "filtro[numero_documento]", params[:filtro].try(:[], :numero_documento), class: 'form-control' %>
          </div>
          <br/>
          <br>
          <div class="input-group col-xs-12 col-md-12 col-lg-12">
            <span class="input-group-addon">Apellido</span><%= text_field_tag "filtro[apellido]", params[:filtro].try(:[], :apellido), class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-offset-1 col-lg-3">
      <div class="form-group">
        <%= label_tag :constancia_domicilio, '&iquest;Acredita residencia en CABA?'.html_safe, class: 'control-label' %>
        <div class="controls"><%= select :filtro, :constancia_domicilio, options_for_select(opciones_booleanas, params[:filtro].try(:[], :constancia_domicilio)), {}, { class: 'form-control' } %></div>
      </div>
      <div class="form-group">
        <%= label_tag :figura_en_padron, '&iquest;Figura en padr&oacute;n?'.html_safe, class: 'control-label' %>
        <div class="controls"><%= select :filtro, :figura_en_padron, options_for_select(opciones_booleanas, params[:filtro].try(:[], :figura_en_padron)), {}, { class: 'form-control' } %></div>
      </div>
      <div class="form-group">
        <%= label_tag :nativo_caba, '&iquest;Es nativo CABA?'.html_safe, class: 'control-label' %>
        <div class="controls"><%= select :filtro, :nativo_caba, options_for_select(opciones_booleanas, params[:filtro].try(:[], :nativo_caba)), {}, { class: 'form-control' } %></div>
      </div>
    </div>

    <div class="col-lg-offset-1 col-lg-3">
      <div class="form-group">
        <label class="control-label">Cargo</label>
        <div class="controls"><%= select :filtro, :cargo, options_for_select(@cargos.map { |c| c.nil? ? [nil, nil]: [c.nombre, c.id]}, params[:filtro].try(:[], :cargo)), {}, { class: 'form-control' } %></div>
      </div>
      <div class="form-group">
        <%= label_tag :cargo_dos_periodos, '&iquest;Mismo cargo en &uacute;ltimos 2 per&iacute;odos?'.html_safe, class: 'control-label' %>
        <div class="controls"><%= select :filtro, :cargo_dos_periodos, options_for_select(opciones_booleanas, params[:filtro].try(:[], :cargo_dos_periodos)), {}, { class: 'form-control' } %></div>
      </div>
      <div class="form-group">
        <%= label_tag :dni_tarjeta, '&iquest;Present&oacute; DNI tarjeta?'.html_safe, class: 'control-label' %>
        <div class="controls"><%= select :filtro, :dni_tarjeta, options_for_select(opciones_booleanas, params[:filtro].try(:[], :dni_tarjeta)), {}, { class: 'form-control' } %></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <%= link_to "<i class='glyphicon glyphicon-search'></i> Buscar".html_safe, '#', class: 'btn btn-default', id: 'link_search_candidaturas' %>
      </div>
    </div>

    <em class="pull-right">Candidaturas encontradas: <strong id="cantidad_candidaturas_top">0</strong></em>
  <% end %>

</div>
<div class="row">
  <div class="col-lg-12">

    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>DNI</th>
          <th>Nombre y Apellido</th>
          <th>Cargo</th>
          <th>Sexo</th>
          <th>Agrupación</th>
          <th>A&ntilde;o</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody id="candidaturas_tbody">
        <%= render @candidaturas %>
      </tbody>
      <tfoot>
        <tr class="well">
          <td colspan="1">&nbsp;</td>
          <td colspan="3">
            <em>Candidaturas encontradas: <strong id="cantidad_candidaturas_bottom"><%= @candidaturas_sin_paginar.count %></strong></em>
          </td>
          <td colspan="3" class="well">
            <%= link_to "<i class='glyphicon glyphicon-list-alt'></i> Exportar a Excel".html_safe, '#', class: 'btn btn-success pull-right', id: 'link_exportar_candidaturas' %>
          </td>
        </tr>
      </tfoot>
    </table>

    <div class="text-center" id="js_paginador">
      <%= paginate @candidaturas if params[:filtro].present? %>
    </div>
  </div>
</div>

app/views/candidaturas/new.html.erb
<h1>New candidatura</h1>

<%= render 'form' %>

<%= link_to 'Back', candidaturas_path %>

app/views/candidaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Persona:</b>
  <%= @candidatura.persona %>
</p>

<p>
  <b>Eleccion cargo:</b>
  <%= @candidatura.eleccion_cargo %>
</p>

<%= link_to 'Edit', edit_candidatura_path(@candidatura) %> |
<%= link_to 'Back', candidaturas_path %>