config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Siel::Application.routes.draw do
  patch 'casos_verificacion/:id/firmar', to: 'casos_verificacion#firmar'
  patch 'casos_verificacion/:id/no_firmar', to: 'casos_verificacion#no_firmar'
  patch 'casos_verificacion/:id/borrar_datos', to: 'casos_verificacion#borrar_datos'

  # resources :verificaciones_firmas do
  #   resources :casos_verificacion
  #   patch :actualizar, on: :collection
  # end

  resources :usuarios do
    get :fuerza, on: :member
    get :find_by_email, on: :collection
    put :blanqueo_clave, on: :member
  end

  get 'usuario/cambiar_contrasenia', to: 'usuarios#cambiar_contrasenia'
  post 'usuario/cambiar_contrasenia', to: 'usuarios#cambiar_contrasenia'

  resources :archivos

  get 'archivos/descargar/:id', to: 'archivos#descargar'

  resources :renglones_padron
  resources :archivo_personas
  resources :archivo_lista_cargos
  resources :cargos

  resources :afiliaciones do
    delete :borrar_afiliaciones, on: :collection
  end

  resources :fiscales do
    delete :destroy_new, on: :member
    delete :borrar_fiscales, on: :collection
    post   :importar_fiscales, on: :collection
    get    :archivo_errores, on: :collection
    get    :exportar, on: :collection
    get    :establecimientos_por_comuna, on: :collection
    get    :cantidad_mesas_establecimiento, on: :collection
  end

  resources :personas do
    get :candidaturas, on: :member
    get :archivos_persona, on: :member
    get :busqueda_persona, on: :collection
    get :busqueda_persona_fiscal, on: :collection
    get :limpiar_formulario, on: :collection
    put :cargar_avatar, on: :collection
    get :ver_adjuntos, on: :member
    get :calcular_comuna, on: :collection
  end

  resources :mesa_extranjeros do
    post :importar_mesas_extranjeros, on: :collection
  end

  resources :importacion_escrutinios, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :calcular_resultados
      get  :reparto_cargos
      post :generar_lista_eleccion_general
      get  :imprimir_reparto_cargos
    end

    collection do
      get :estado_importacion_archivo
    end
  end

  # TODO: ver si hay que borrar, los documento se suben por el controller ArchivoPersonas
  post 'personas/adjuntar_documento', to: 'personas#adjuntar_documento'
  get 'personas/descargar_documento/:archivo_persona_id', to: 'personas#descargar_documento'

  resources :padrones do
    get :renglones_importados, on: :member
  end
  get 'padrones/importar/:index', to: 'padrones#importar'

  resources :candidaturas do
    post :renunciar, on: :member
    get  :cumple_ley_cupos, on: :member
    get  :cumple_minimo, on: :member
    get  :eventos, on: :collection
    post :sugerir_orden, on: :collection
    post :aceptar_correccion_cupo, on: :collection
    post :buscar_por_documento, on: :collection
    put  :aplicar_validaciones, on: :collection
    post :cambiar_orden, on: :collection
  end
  get 'candidaturas/importar/lista', to: 'candidaturas#importar_lista'
  post 'candidaturas/procesar_archivo', to: 'candidaturas#procesar_archivo'
  post 'candidaturas/auto_ordenamiento', to: 'candidaturas#auto_ordenamiento'
  post 'candidaturas/deshacer_ordenamiento', to: 'candidaturas#deshacer_ordenamiento'
  post 'candidaturas/subir', to: 'candidaturas#subir'
  post 'candidaturas/bajar', to: 'candidaturas#bajar'
  post 'candidaturas/filtrar'
  post 'candidaturas/oficializar_lista'
  post 'candidaturas/desoficializar_lista'

  get 'expedientes/buscar'

  resources :fuerzas do
    resources :infracciones
    get    :candidaturas, on: :member
    get    :apoderados, on: :member
    get    :agregar_apoderado, on: :collection
    post   :listado_apoderados, on: :collection
    get    :select_fuerzas, on: :collection
    patch  :editar_escudo
    delete :eliminar_escudo

    member do
      delete :baja
    end
  end

  resources :fuerza_eleccion, only: [:update]

  post 'fuerzas/filtrar'

  resources :elecciones do
    get 'descargar_resolucion'
    get :fuerzas, on: :member
    get :cargos, on: :member
    get :exportar_apoderados, on: :member
    get :actual, on: :collection

    post   :cargar_reparto, on: :member
    post   :grabar_reparto, on: :member
    delete :destroy_reparto, on: :member
    get    :reparto_anexo_1, on: :member
    get    :reparto_anexo_2, on: :member
    get    :reparto_anexo_2_2009, on: :member
    get    :reparto_anexo_3_2009, on: :member
    get    :reparto_anexo_4_2009, on: :member
    get    :reparto_anexo_5_2009, on: :member
  end
  post 'elecciones/filtrar'

  resources :eleccion_cargos
  resources :incidencias do
    delete :borrar_incidencias, on: :collection
  end

  resources :listas do
    resources :lista_cargos do
      member do
        post :borrar_candidaturas
        post :borrar_adhesiones
        post :importar_personas
        get  :estado_importacion_archivo
        get  :descargar_archivo_errores_importacion
        post :validar
        post :cerrar_lista
        post :abrir_lista
        get  :imprimir_candidaturas
        get  :exportar_adhesiones
        get  :descargar_exportacion_adhesiones
        get  :imprimir_auto_ordenamiento
        get  :versiones
        get  :exportar_versiones
        get  :descargar_exportacion_versiones
        get  :observaciones
      end
    end

    member do
      post :validar
      post :oficializar
      post :desoficializar
      get  :imprimir_lista_prototipo
      get  :imprimir_acta_presentacion
      get  :bitacora
      put  :asignar_numero_escrutinio
    end

    collection do
      get :seccion_cargos_habilitados
      get :imprimir_resolucion_oficializacion
      get :imprimir_comunicado_articulo_26
    end
  end

  resources :listas_generales do
    resources :lista_cargos_generales do
      member do
        get  :imprimir_lista_general
      end
    end
  end

  resources :observaciones, only: [:index, :edit, :update] do
    collection do
      post :subsanar
    end
  end

  resources :adhesiones, only: [:index, :create, :destroy]
  resources :configuraciones, only: [:show, :update]
  resources :siel_archivos
  resources :registro_candidaturas do
    delete :borrar_registros_candidaturas, on: :collection
  end

  resources :calles, only: [:index]

  resources :antecedentes_penales do
    member do
      post :enviar_solicitud
      get :descargar_antecedente_penal_pdf
    end
  end

  root to: 'root#index'

  # Rutas del controller admin
  post 'admin/login'
  post 'admin/login_extranet'
  get  'admin/login'
  get  'admin/logout'

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/lista_cargos_controller.rb
class ListaCargosController < ApplicationController
  authorize_resource
  before_filter :cargar_lista_cargo_y_validar
  before_filter :validar_carga_candidaturas_eleccion, except: [:show, :versiones, :exportar_versiones, :observaciones, :exportar_adhesiones, :descargar_exportacion_adhesiones, :imprimir_candidaturas]

  def show
    authorize! :manage, @lista_cargo
    @pagina_adhesiones = params[:pagina_adhesiones] || 1
    @pagina_versiones = params[:pagina_versiones] || 1
    @lista_filtrada = params[:lista_filtrada]
    @lista = @lista_cargo.lista
    @cargo = @lista_cargo.cargo
    @adhesiones_search = AdhesionesSearch.new(params.try(:[], :adhesiones_search) || {})
    # @versiones = PaperTrail::Version.versiones_lista_cargo(@lista_cargo.id).page(@pagina_versiones)

    @pagina_observaciones = 1
    @observacion = Observacion.new
    @observaciones_search = ObservacionesSearch.new
    @observaciones = Observacion.where(lista_cargo_id: @lista_cargo.id).page(1)

    authorize! :manage, @lista

    # Buscamos la elección, la fuerza politica y los cargos correspondientes
    @eleccion = @lista_cargo.eleccion
    cargar_fuerza_cargos

    @candidatura = Candidatura.new(lista_cargo: @lista_cargo, persona: Persona.new(archivos_persona: [ArchivoPersona.new]), cargo: @cargo)
    @adhesion = Adhesion.new(lista_cargo: @lista_cargo, persona: Persona.new(archivos_persona: [ArchivoPersona.new]))

    @cantidad_adhesiones = @lista_cargo.adhesiones.count

    @importar_precandidatos_id = @lista_cargo.importacion_job('Candidatura')
    @importar_adherentes_id = @lista_cargo.importacion_job('Adhesion')

    @adhesiones = @adhesiones_search.results.lista_cargo(@lista_cargo).orden_creacion.page(@pagina_adhesiones).includes(:persona)

    respond_to do |format|
      format.html do
        render :show
      end
    end
  end

  def importar_personas
    authorize! :manage, @lista_cargo
    raise "Importación inválida" unless params[:tipo].downcase =~ /adhesion|candidatura/

    @tipo_importacion = params[:tipo]
    @limpiar_cargo = params[:limpiar_cargo] == 'true'
    @formato_archivo_incorrecto = false

    if validar_formato_archivo_importacion(params[:archivo])
      guardar_archivo(params[:archivo], @lista_cargo.path_archivo_importar(@tipo_importacion))

      @job_id = if @tipo_importacion.eql? 'Adhesion'
                  ImportarAdherentesJob.perform_async(@lista_cargo.id, current_user.nombre_usuario, @limpiar_cargo)
                else
                  ImportarPrecandidatosJob.perform_async(@lista_cargo.id, current_user.nombre_usuario, @limpiar_cargo)
                end

      @lista_cargo.setear_importacion(@tipo_importacion, @job_id)
    else
      @formato_archivo_incorrecto = true
    end

    respond_to do |format|
      format.js
    end
  end

  def estado_importacion_archivo
    @pagina_adhesiones = params[:pagina_adhesiones] || 1
    @lista = @lista_cargo.lista
    @job_id = params[:job_id]
    @tab = params[:tab]

    @job_completado = Sidekiq::Status.complete?(@job_id)
    @job_progreso = Sidekiq::Status.at(@job_id)
    @job_error = Sidekiq::Status.failed?(@job_id)
    @job_estado = Sidekiq::Status.status(@job_id)

    if @job_completado
      @adhesiones_search = AdhesionesSearch.new(params.try(:[], :adhesiones_search) || {})
      @cantidad_adhesiones = @lista_cargo.adhesiones.count
      @adhesiones = @lista_cargo.adhesiones.orden_creacion.page(@pagina_adhesiones).includes(:persona) if @tab == 'adhesiones'

      if File.exist?(@lista_cargo.path_archivo_con_errores_importacion(((@tab == 'candidaturas') ? 'Candidatura' : 'Adhesion')))
        flash.now[:sweet_alert_warning] = 'La importación se completó. Existen registros con error. Descargue el archivo para ver los detalles'
      else
        flash.now[:notice] = 'La importación se realizó satisfactoriamente.'
      end
    elsif @job_error or @job_estado.nil?
      @lista_cargo.actualizar_importacion(((@tab == 'candidaturas') ? 'Candidatura' : 'Adhesion'))
    end

    respond_to do |format|
      format.js
    end
  end

  def descargar_archivo_errores_importacion
    nombre_archivo = if params[:modelo].eql? 'Adhesion'
                       "errores_importacion_adhesiones_#{@lista_cargo.cargo.nombre_snake_case}.xls"
                     else
                       "errores_importacion_precandidaturas_#{@lista_cargo.cargo.nombre_snake_case}.xls"
                     end

    send_file(
      @lista_cargo.path_archivo_con_errores_importacion(params[:modelo]),
      filename: I18n.transliterate(nombre_archivo)
    )
  end

  def borrar_candidaturas
    authorize! :manage, @lista_cargo
    @lista_cargo.borrar_candidaturas

    render json: { msg: 'Se borraron las candidaturas de la lista.' }, status: :ok
  end

  def borrar_adhesiones
    authorize! :manage, @lista_cargo
    @lista_cargo.borrar_adhesiones
    Adhesion.asignar_adhesiones_multiples_default!
    Adhesion.calculo_incremento_adhesiones_multiples!

    render json: { msg: 'Se borraron las adhesiones de la lista.' }, status: :ok
  end

  def imprimir_candidaturas
    @lista = @lista_cargo.lista
    data = StringIO.new
    excel = ListaPrototipoExcel.new(@lista_cargo.lista, @lista_cargo).imprimir
    excel.write(data)

    respond_to do |format|
      format.xls do
        send_data data.string, filename: I18n.transliterate("Candidatos - #{@lista.fuerza_nombre} - #{@lista.nombre} - #{@lista_cargo.cargo_nombre.gsub(Cargo::CARGOS[:diputado], 'Legisladores')}.xls"), type: 'application/xls'
      end
    end
  end

  def exportar_adhesiones
    @lista_cargo = ListaCargo.find(params[:id])
    TablaAdhesionesPdf.new(@lista_cargo)
    @path = @lista_cargo.path_exportacion_adhesiones

    respond_to do |format|
      format.js { render 'exportar_adhesiones' }
    end
  end

  def descargar_exportacion_adhesiones
    @lista_cargo = ListaCargo.find(params[:id])
    @path = params[:path]
    send_data File.read(@path), filename: I18n.transliterate("Adherentes - #{@lista_cargo.fuerza_nombre} - #{@lista_cargo.lista_nombre} - #{@lista_cargo.cargo_nombre.gsub(Cargo::CARGOS[:diputado], 'Legisladores')}.pdf"), type:  'application/pdf'
    FileUtils.rm(@path)
  end

  def validar
    authorize! :manage, @lista_cargo
    @tab = params[:tab]
    @errores, @alertas = @lista_cargo.send("validar_#{@tab}!")

    @titulo_alerta = I18n.t("activerecord.errors.models.lista_cargo.estados.#{@lista_cargo.send("estado_#{@tab}")}_titulo", categoria: I18n.t(@tab).capitalize)

    respond_to do |format|
      format.js
    end
  end

  def cerrar_lista
    authorize! :manage, @lista_cargo
    @tab = params[:tab]
    @lista_cargo.send("cerrar_#{@tab}!")

    @lista_cargo.errors.empty? ? flash[:notice] = "#{I18n.t(@tab).capitalize} han sido cerradas correctamente" : flash[:error] = @lista_cargo.errors[:cerrar_lista].try(:first)
    params_redirect = { controller: 'lista_cargos', action: 'show', id: @lista_cargo.id, lista_id: @lista_cargo.lista_id, tab: @tab }
    params_redirect[:origin] = 'cerrar_lista' unless @lista_cargo.send("estado_#{@tab}_cerrada?")

    if current_user.lista_partidaria? && @lista_cargo.lista_cerrada?
      Usuario.find(current_user.id).update_attribute(:habilitado, false)
      redirect_to admin_logout_path(logout_message: 'Ha completado la carga de la Lista. Su usuario quedo deshabilitado. Ante cualquier duda o reclamo puede dirigirse a la Mesa de Entradas Electoral, sita en Cerrito 760 Planta Baja, o comuníquese por teléfono al 4370-8500 interno 1903 o interno 777, o por email a siel@tsjbaires.gov.ar')
    else
      redirect_to params_redirect
    end
  end

  def abrir_lista
    authorize! :manage, @lista_cargo
    @tab = params[:tab]
    estado_apertura = params[:abierta_lista] == 'true' ? Lista::ESTADOS[:ABIERTA] : Lista::ESTADOS[:REABIERTA]
    @lista_cargo.send("abrir_#{@tab}!",  estado_apertura)
    flash[:notice] = "#{I18n.t(@tab).capitalize} han sido abiertas correctamente"

    redirect_to controller: 'lista_cargos', action: 'show', id: @lista_cargo.id, lista_id: @lista_cargo.lista_id, tab: @tab
  end

  def imprimir_auto_ordenamiento
    @ordenadas = @lista_cargo.candidaturas.sort
    Candidatura.sugerir_orden_cargo(@ordenadas)
    @ordenadas.sort!

    @originales = @lista_cargo.candidaturas.reload.sort

    respond_to do |format|
      format.pdf do
        send_data TablasComparativasPdf.new(@lista_cargo, @originales, @ordenadas).render, filename: I18n.transliterate("Auto Ordenamiento de Candidatos - #{@lista_cargo.lista_nombre} - #{@lista_cargo.cargo_nombre.gsub(Cargo::CARGOS[:diputado], 'Legisladores')}.pdf"), type: 'application/pdf'
      end
    end
  end

  def versiones
    @bitacora_search = BitacoraSearch.new(parametros_bitacora_search)
    @versiones = @bitacora_search.results
    @versiones_count = @versiones.count
    @versiones = @versiones.page(params[:pagina_versiones])
    @pagina = params[:pagina_versiones].to_i + 1

    respond_to do |format|
      format.js { render 'versiones' }
    end
  end

  def exportar_versiones
    @lista_cargo = ListaCargo.find(params[:id])
    @bitacora_search = BitacoraSearch.new(parametros_bitacora_search)
    @versiones = @bitacora_search.results
    @path = BitacoraExcel.exportar(@lista_cargo, @versiones)

    respond_to do |format|
      format.js { render 'exportar_versiones' }
    end
  end

  def descargar_exportacion_versiones
    @lista_cargo = ListaCargo.find(params[:id])
    @path = params[:path]
    archivo_con_errores = Spreadsheet.open(@path)
    data = StringIO.new
    archivo_con_errores.write(data)
    send_data data.string, filename: I18n.transliterate("Bitácora de #{@lista_cargo.fuerza_nombre} - #{@lista_cargo.lista_nombre} - #{@lista_cargo.cargo_nombre}.xls"), type:  'application/vnd.ms-excel'
    FileUtils.rm(@path)
  end

  def observaciones
    @pagina_observaciones = 1
    ids_candidaturas_con_observaciones = Observacion.where(lista_cargo_id: @lista_cargo.id).select('DISTINCT observable_id')

app/helpers/lista_cargos_helper.rb
module ListaCargosHelper

  def path_eliminar_personas_en_lista(lista, lista_cargo, tab)
    if tab == 'candidaturas'
      borrar_candidaturas_lista_lista_cargo_path(lista, lista_cargo)
    elsif tab == 'adhesiones'
      borrar_adhesiones_lista_lista_cargo_path(lista, lista_cargo)
    end
  end

  def path_imprimir_personas_en_lista(lista, lista_cargo, tab)
    if tab == 'candidaturas'
      imprimir_candidaturas_lista_lista_cargo_path(lista, lista_cargo, format: :xls)
    elsif tab == 'adhesiones'
      exportar_adhesiones_lista_lista_cargo_path(lista, lista_cargo)
    end
  end

end

app/views/lista_cargos/modals/_edit_observacion_modal.html.erb
<div class="modal fade" id="modal-observacion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content js-modal-observacion">
      <%= render 'lista_cargos/modals/observacion_form', observacion: observacion %>
    </div>
  </div>
</div>

app/views/lista_cargos/modals/_observacion_form.html.erb
<%= form_for observacion, url: observacion_path, method: :put, remote: true do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Añadir Comentarios</h4>
  </div>

  <div class="modal-body">

    <div class="form-group">
      <div class="row">
        <label class="col-md-4 control-label">Comentarios</label>
        <div class="col-md-8">
          <%= f.text_area :comentarios, class: "form-control" %>
        </div>
      </div>
    </div>

  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lista_cargos/modals/_tabla_comparativa.html.erb
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Ordenamiento Sugerido - Cargo <%= originales.first.cargo.nombre.gsub(Cargo::CARGOS[:diputado], 'Legisladores') %></h4>
  </div>

  <div class="modal-body">
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">

          <div class="panel-heading bg-rojo">
            <h3 class="blanco">
              <strong>
                Lista Original
              </strong>
            </h3>
          </div>

          <div class="panel-body">
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th class="text-center">Orden</th>
                  <th class="text-center">DNI</th>
                  <th class="text-center">Precandidato/a</th>
                  <th class="text-center">Sexo</th>
                </tr>
              </thead>
              <tbody>
                <% originales.each_with_index do |c, i| %>
                  <% if i == c.cargo.cantidad_minima %>
                    <tr><td colspan=4></td></tr>
                  <% end %>
                  <tr class="<%= (ordenadas[i].persona != originales[i].persona) ? "remarcado-verde": "" %> <%= originales[i].decorate.color_sexo %>">
                    <!-- <td><%= orden(c) %></td> -->
                    <td class="text-center"><%= c.decorate.orden %></td>
                    <td class="text-right"><%= c.persona.numero_documento %></td>
                    <td class="text-left"><%= c.persona.nombres %> <%= c.persona.apellidos %></td>
                    <td class="text-center"><%= c.persona.sexo %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

      </div>

      <div class="col-md-6">

        <div class="panel panel-default">

          <div class="panel-heading bg-verde">
            <h3 class="blanco">
              <strong>
                Lista Sugerida
              </strong>
            </h3>
          </div>

          <div class="panel-body">
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th class="text-center">Orden</th>
                  <th class="text-center">DNI</th>
                  <th class="text-center">Precandidato/a</th>
                  <th class="text-center">Sexo</th>
                </tr>
              </thead>
              <tbody>
                <% ordenadas.each_with_index do |c, i| %>
                  <% if i == c.cargo.cantidad_minima %>
                    <tr><td colspan=4></td></tr>
                  <% end %>
                  <tr class="<%= (ordenadas[i].persona != originales[i].persona) ? "remarcado-verde": "" %> <%= ordenadas[i].decorate.color_sexo %>">
                    <!-- <td><%= orden(c) %></td> -->
                    <td class="text-center"><%= c.decorate.orden %></td>
                    <td class="text-right"><%= c.persona.numero_documento %></td>
                    <td class="text-left"><%= c.persona.nombres %> <%= c.persona.apellidos %></td>
                    <td class="text-center"><%= c.persona.sexo %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="modal-footer">
    <%= link_to "Aceptar Sugerencia", candidaturas_auto_ordenamiento_path(lista_cargo_id: lista_cargo.id), method: :post, remote: true, class: 'btn btn-primary' %>
    <%= link_to "Descargar Sugerencia <i class='fa fa-download'></i>".html_safe, imprimir_auto_ordenamiento_lista_lista_cargo_path(lista_cargo.lista, lista_cargo, format: :pdf), class: "btn btn-sm btn-default" %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
  </div>
</div>

app/views/lista_cargos/modals/_tabla_correccion_cupo.html.erb
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Correciòn Sugerida - Cargo <%= originales.first.cargo.nombre.gsub(Cargo::CARGOS[:diputado], 'Legisladores') %></h4>
  </div>

  <div class="modal-body">
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">

          <div class="panel-heading bg-rojo">
            <h3 class="blanco">
              <strong>
                Lista Original
              </strong>
            </h3>
          </div>

          <div class="panel-body">
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th class="text-center">Orden</th>
                  <th class="text-center">DNI</th>
                  <th class="text-center">Precandidato/a</th>
                  <th class="text-center">Sexo</th>
                </tr>
              </thead>
              <tbody>
                <% originales.each_with_index do |c, i| %>
                  <% if i == c.cargo.cantidad_minima %>
                    <tr><td colspan=4></td></tr>
                  <% end %>
                  <tr class="<%= (!cupo_corregido.include?(c)) ? "remarcado-rojo": "" %> <%= c.decorate.color_sexo %>">
                    <!-- <td><%= orden(c) %></td> -->
                    <td class="text-center"><%= c.decorate.orden %></td>
                    <td class="text-right"><%= c.persona.numero_documento %></td>
                    <td class="text-left"><%= c.persona.nombres %> <%= c.persona.apellidos %></td>
                    <td class="text-center"><%= c.persona.sexo %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

      </div>

      <div class="col-md-6">

        <div class="panel panel-default">

          <div class="panel-heading bg-verde">
            <h3 class="blanco">
              <strong>
                Lista Sugerida
              </strong>
            </h3>
          </div>

          <div class="panel-body">
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th class="text-center">Orden</th>
                  <th class="text-center">DNI</th>
                  <th class="text-center">Precandidato/a</th>
                  <th class="text-center">Sexo</th>
                </tr>
              </thead>
              <tbody>
                <% cupo_corregido.each_with_index do |c, i| %>
                  <% if i == c.cargo.cantidad_minima %>
                    <tr><td colspan=4></td></tr>
                  <% end %>
                  <tr class="<%= c.decorate.color_sexo %>">
                  <tr class="<%= (cupo_corregido[i].persona != originales[i].persona) ? "remarcado-verde": "" %> <%= c.decorate.color_sexo %>">
                    <!-- <td><%= orden(c) %></td> -->
                    <td class="text-center"><%= c.decorate.orden %></td>
                    <td class="text-right"><%= c.persona.numero_documento %></td>
                    <td class="text-left"><%= c.persona.nombres %> <%= c.persona.apellidos %></td>
                    <td class="text-center"><%= c.persona.sexo %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="modal-footer">
    <%= link_to "Aceptar Sugerencia", aceptar_correccion_cupo_candidaturas_path(lista_cargo_id: lista_cargo.id), method: :post, remote: true, class: 'btn btn-primary' %>
    <%= link_to "Descargar Sugerencia <i class='fa fa-download'></i>".html_safe, imprimir_auto_ordenamiento_lista_lista_cargo_path(lista_cargo.lista, lista_cargo, format: :pdf), class: "btn btn-sm btn-default" %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
  </div>
</div>