config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Siel::Application.routes.draw do
  patch 'casos_verificacion/:id/firmar', to: 'casos_verificacion#firmar'
  patch 'casos_verificacion/:id/no_firmar', to: 'casos_verificacion#no_firmar'
  patch 'casos_verificacion/:id/borrar_datos', to: 'casos_verificacion#borrar_datos'

  # resources :verificaciones_firmas do
  #   resources :casos_verificacion
  #   patch :actualizar, on: :collection
  # end

  resources :usuarios do
    get :fuerza, on: :member
    get :find_by_email, on: :collection
    put :blanqueo_clave, on: :member
  end

  get 'usuario/cambiar_contrasenia', to: 'usuarios#cambiar_contrasenia'
  post 'usuario/cambiar_contrasenia', to: 'usuarios#cambiar_contrasenia'

  resources :archivos

  get 'archivos/descargar/:id', to: 'archivos#descargar'

  resources :renglones_padron
  resources :archivo_personas
  resources :archivo_lista_cargos
  resources :cargos

  resources :afiliaciones do
    delete :borrar_afiliaciones, on: :collection
  end

  resources :fiscales do
    delete :destroy_new, on: :member
    delete :borrar_fiscales, on: :collection
    post   :importar_fiscales, on: :collection
    get    :archivo_errores, on: :collection
    get    :exportar, on: :collection
    get    :establecimientos_por_comuna, on: :collection
    get    :cantidad_mesas_establecimiento, on: :collection
  end

  resources :personas do
    get :candidaturas, on: :member
    get :archivos_persona, on: :member
    get :busqueda_persona, on: :collection
    get :busqueda_persona_fiscal, on: :collection
    get :limpiar_formulario, on: :collection
    put :cargar_avatar, on: :collection
    get :ver_adjuntos, on: :member
    get :calcular_comuna, on: :collection
  end

  resources :mesa_extranjeros do
    post :importar_mesas_extranjeros, on: :collection
  end

  resources :importacion_escrutinios, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :calcular_resultados
      get  :reparto_cargos
      post :generar_lista_eleccion_general
      get  :imprimir_reparto_cargos
    end

    collection do
      get :estado_importacion_archivo
    end
  end

  # TODO: ver si hay que borrar, los documento se suben por el controller ArchivoPersonas
  post 'personas/adjuntar_documento', to: 'personas#adjuntar_documento'
  get 'personas/descargar_documento/:archivo_persona_id', to: 'personas#descargar_documento'

  resources :padrones do
    get :renglones_importados, on: :member
  end
  get 'padrones/importar/:index', to: 'padrones#importar'

  resources :candidaturas do
    post :renunciar, on: :member
    get  :cumple_ley_cupos, on: :member
    get  :cumple_minimo, on: :member
    get  :eventos, on: :collection
    post :sugerir_orden, on: :collection
    post :aceptar_correccion_cupo, on: :collection
    post :buscar_por_documento, on: :collection
    put  :aplicar_validaciones, on: :collection
    post :cambiar_orden, on: :collection
  end
  get 'candidaturas/importar/lista', to: 'candidaturas#importar_lista'
  post 'candidaturas/procesar_archivo', to: 'candidaturas#procesar_archivo'
  post 'candidaturas/auto_ordenamiento', to: 'candidaturas#auto_ordenamiento'
  post 'candidaturas/deshacer_ordenamiento', to: 'candidaturas#deshacer_ordenamiento'
  post 'candidaturas/subir', to: 'candidaturas#subir'
  post 'candidaturas/bajar', to: 'candidaturas#bajar'
  post 'candidaturas/filtrar'
  post 'candidaturas/oficializar_lista'
  post 'candidaturas/desoficializar_lista'

  get 'expedientes/buscar'

  resources :fuerzas do
    resources :infracciones
    get    :candidaturas, on: :member
    get    :apoderados, on: :member
    get    :agregar_apoderado, on: :collection
    post   :listado_apoderados, on: :collection
    get    :select_fuerzas, on: :collection
    patch  :editar_escudo
    delete :eliminar_escudo

    member do
      delete :baja
    end
  end

  resources :fuerza_eleccion, only: [:update]

  post 'fuerzas/filtrar'

  resources :elecciones do
    get 'descargar_resolucion'
    get :fuerzas, on: :member
    get :cargos, on: :member
    get :exportar_apoderados, on: :member
    get :actual, on: :collection

    post   :cargar_reparto, on: :member
    post   :grabar_reparto, on: :member
    delete :destroy_reparto, on: :member
    get    :reparto_anexo_1, on: :member
    get    :reparto_anexo_2, on: :member
    get    :reparto_anexo_2_2009, on: :member
    get    :reparto_anexo_3_2009, on: :member
    get    :reparto_anexo_4_2009, on: :member
    get    :reparto_anexo_5_2009, on: :member
  end
  post 'elecciones/filtrar'

  resources :eleccion_cargos
  resources :incidencias do
    delete :borrar_incidencias, on: :collection
  end

  resources :listas do
    resources :lista_cargos do
      member do
        post :borrar_candidaturas
        post :borrar_adhesiones
        post :importar_personas
        get  :estado_importacion_archivo
        get  :descargar_archivo_errores_importacion
        post :validar
        post :cerrar_lista
        post :abrir_lista
        get  :imprimir_candidaturas
        get  :exportar_adhesiones
        get  :descargar_exportacion_adhesiones
        get  :imprimir_auto_ordenamiento
        get  :versiones
        get  :exportar_versiones
        get  :descargar_exportacion_versiones
        get  :observaciones
      end
    end

    member do
      post :validar
      post :oficializar
      post :desoficializar
      get  :imprimir_lista_prototipo
      get  :imprimir_acta_presentacion
      get  :bitacora
      put  :asignar_numero_escrutinio
    end

    collection do
      get :seccion_cargos_habilitados
      get :imprimir_resolucion_oficializacion
      get :imprimir_comunicado_articulo_26
    end
  end

  resources :listas_generales do
    resources :lista_cargos_generales do
      member do
        get  :imprimir_lista_general
      end
    end
  end

  resources :observaciones, only: [:index, :edit, :update] do
    collection do
      post :subsanar
    end
  end

  resources :adhesiones, only: [:index, :create, :destroy]
  resources :configuraciones, only: [:show, :update]
  resources :siel_archivos
  resources :registro_candidaturas do
    delete :borrar_registros_candidaturas, on: :collection
  end

  resources :calles, only: [:index]

  resources :antecedentes_penales do
    member do
      post :enviar_solicitud
      get :descargar_antecedente_penal_pdf
    end
  end

  root to: 'root#index'

  # Rutas del controller admin
  post 'admin/login'
  post 'admin/login_extranet'
  get  'admin/login'
  get  'admin/logout'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/incidencia.rb
# == Schema Information
#
# Table name: incidencias
#
#  id               :integer          not null, primary key
#  tipo_documento   :string(255)
#  numero_documento :integer
#  sexo             :string(255)
#  tipo_incidencia  :string(255)
#  eleccion_id      :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  descripcion      :string(255)
#  cargo_id         :integer
#

class Incidencia < ActiveRecord::Base

  TIPOS_INCIDENCIAS = { 'Deudor Alimentario' => 'DEUDOR_ALIMENTARIO',
                        'Inhabilitado' => 'INHABILITADO',
                        'Reelección Inhabilitada' => 'REINCIDENCIA_CARGO' }

  attr_accessible :tipo_documento, :numero_documento, :sexo, :tipo_incidencia, :eleccion,
                  :eleccion_id, :descripcion, :cargo_id, :cargo

  belongs_to :eleccion
  belongs_to :cargo

  validates :numero_documento, :sexo, :tipo_incidencia, :eleccion_id, presence: true
  validates :cargo_id, presence: true, if: "tipo_incidencia == Incidencia::TIPOS_INCIDENCIAS['Reelección Inhabilitada']"
  validates :tipo_incidencia, inclusion: { in: TIPOS_INCIDENCIAS.values }

  # Metodo para procesar y generar las incidencias en la base de datos
  # @params incidencia [Incidencia] modelo que contiene la info generico (eleccion y tipo incidencia)
  # @params datos [String] con formato NUMERO_DOCUMENTO, TIPO_DOCUMENTO, SEXO concatenados para generar multiples incidencias
  # @return [Array] que contiene las incidencias que no se puede crear en base a las validaciones
  def self.procesar_incidencias(incidencia, datos)
    lista_documentos = datos.strip.split(/[\n\r]/).delete_if(&:blank?)

    incidencias_invalidas = []
    incidencias_validas = []
    lista_documentos.each do |info|
      numero_documento, tipo_documento, sexo, descripcion = info.gsub(/\s+/, '').split(',').map(&:upcase)
      sexo = 'NA' if sexo.blank?
      tipo_documento = tipo_documento.include?('DNI') ? 'DNI' : 'L'

      if numero_documento.try(:match, /^(\d)+$/) && sexo.try(:match, /M|F|NA/) && Persona::DOCUMENTO_TIPOS.values.include?(tipo_documento)
        unless Incidencia.where(tipo_incidencia: incidencia[:tipo_incidencia], eleccion_id: incidencia[:eleccion_id],
                                numero_documento: numero_documento, sexo: sexo, tipo_documento: tipo_documento).exists?

          incidencias_validas << Incidencia.new(tipo_incidencia: incidencia[:tipo_incidencia], eleccion_id: incidencia[:eleccion_id], cargo_id: incidencia[:cargo_id],
                             numero_documento: numero_documento, sexo: sexo, tipo_documento: tipo_documento, descripcion: descripcion)
        end
      else
        incidencias_invalidas << "#{numero_documento}, #{tipo_documento}, #{sexo}"
      end
    end

    Incidencia.import incidencias_validas, batch_size: 5000

    incidencias_invalidas
  end

  #--------------------------------------------------------------------------------#
  # Class Methods
  #--------------------------------------------------------------------------------#
  def self.search_by_filter(filtro_incidencia)
    incidencias = self

    if filtro_incidencia.tipo_incidencia.present?
      incidencias = incidencias.where(tipo_incidencia: filtro_incidencia.tipo_incidencia)
    end

    if filtro_incidencia.numero_documento.present?
      incidencias = incidencias.where(numero_documento: filtro_incidencia.numero_documento)
    end

    if filtro_incidencia.eleccion_id.present?
      incidencias = incidencias.where(eleccion_id: filtro_incidencia.eleccion_id)
    end

    incidencias.order('created_at DESC')
  end
end

app/controllers/incidencias_controller.rb
class IncidenciasController < ApplicationController

  def index
    @filtro_incidencias = Incidencia.new(incidencia_params)

    @incidencias =  if incidencia_params
                      Incidencia.search_by_filter(@filtro_incidencias).page params[:page]
                    else
                      Incidencia.all.page params[:page]
                    end
  end

  def new
    @incidencia = Incidencia.new
  end

  def create
    @incidencias_invalidas = Incidencia.procesar_incidencias(params[:incidencia], params[:datos])

    if @incidencias_invalidas.empty?
      flash[:info] = "Incidencias cargadas exitosamente."
      redirect_to incidencias_path
    else
      @incidencia = Incidencia.new(params.require(:incidencia).permit(:tipo_incidencia, :eleccion_id))

      total_incidencias_cargadas = params[:datos].strip.split(/[\n\r]/).delete_if(&:blank?).size - @incidencias_invalidas.size
      if total_incidencias_cargadas > 0
        flash[:warning] = "#{total_incidencias_cargadas} Incidencias cargadas exitosamente. <br/><br/>" +
                          "#{@incidencias_invalidas.size} Incidencias inválidas: <br/>#{@incidencias_invalidas.join(' , ')}"
      else
        flash[:error] = "#{@incidencias_invalidas.size} Incidencia/s inválida/s: <br/>#{@incidencias_invalidas.join(' , ')}"
      end

      render 'new'
    end
  end

  def destroy
    @incidencia = Incidencia.find(params[:id])
    @incidencia.destroy

    redirect_to incidencias_path
  end

  def borrar_incidencias
    if params[:incidencia].blank?
      Incidencia.delete_all
    else
      @filtro_incidencias = Incidencia.new(incidencia_params)
      Incidencia.search_by_filter(@filtro_incidencias).delete_all
    end

    redirect_to incidencias_path(incidencia: params[:incidencia])
  end

  private

  def incidencia_params
    params.require(:incidencia).permit(:numero_documento, :tipo_incidencia, :eleccion_id) if params[:incidencia]
  end

end

app/helpers/incidencias_helper.rb
module IncidenciasHelper
end

app/views/incidencias/_filters.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Filtros</h3>
  </div>
  <div class="panel-body">
    <%= form_for @filtro_incidencias, url: incidencias_path, method: "get", html: {class: "form-inline", role: "form"} do |f| %>
      <div class="row">
        <div class="col-md-3">
          <div class="form-group">
            <%= f.select :eleccion_id, options_for_select(Eleccion.por_tipo(Eleccion::TIPOS[:paso]).collect {|el| [el.descripcion, el.id]}, f.object.eleccion_id),
                                       {:include_blank => 'Eleccion...'}, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-3">
          <div class="form-group">
            <%= f.select :tipo_incidencia, options_for_select(Incidencia::TIPOS_INCIDENCIAS, f.object.tipo_incidencia), {:include_blank => 'Tipo Incidencia...'}, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-3">
          <div class="form-group">
            <%= f.text_field :numero_documento, placeholder: "Número documento", class: "form-control", pattern: '[0-9]*'%>
          </div>
        </div>


        <div class="col-md-3">
          <div class="pull-right">
            <%= link_to "Borrar Filtro", incidencias_path , :class => "btn"%>

            <%= button_tag(type: "submit", class: "btn btn-info") do %>
              Buscar <i class='glyphicon glyphicon-search'></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/incidencias/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Listado de Incidencias</h1>
    </div>
  </div>
</div>

<%= render partial: 'filters' %>

<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <%= link_to "Borrar Incidencias <i class='fa fa-minus-circle'></i>".html_safe, borrar_incidencias_incidencias_path(incidencia: params[:incidencia]), class: 'btn btn-danger', method: :delete %>
      <%= link_to "Cargar Incidencias <i class='fa fa-plus'></i>".html_safe, new_incidencia_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-12">

    <% if @incidencias.empty? %>
      <div class="alert alert-info" role="alert">
        No hay incidencias cargadas en el sistema.
      </div>
    <% else %>
      <table class="table table-striped table-condensed">
        <thead>
          <tr>
            <th> Nro. </th>
            <th> Tipo Incidencia </th>
            <th> Descripción </th>
            <th> Documento </th>
            <th> Tipo Documento </th>
            <th> Sexo </th>
            <th> Eleccion </th>
            <th style="text-align: center;"> Acciones </th>
          </tr>
        </thead>

        <tbody>
          <% @incidencias.each_with_index do |incidencia, index| %>
            <tr>
              <td> <%= index + 1 %> </td>
              <td> <%= Incidencia::TIPOS_INCIDENCIAS.key(incidencia.tipo_incidencia) %> </td>
              <td> <%= incidencia.descripcion %> </td>
              <td> <%= incidencia.numero_documento %> </td>
              <td> <%= incidencia.tipo_documento %> </td>
              <td> <%= incidencia.sexo %> </td>
              <td> <%= incidencia.eleccion.descripcion %> </td>
              <td style="text-align: center;">
                <%= link_to "<i class='glyphicon glyphicon-remove'></i>".html_safe, incidencia_path(incidencia),
                      data: { confirm: 'Desea borrar la incidencia?' }, :method => :delete, :class => 'btn btn-danger', :rel => 'tooltip', :title => 'Borrar Incidencia' %>
              <td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @incidencias %>
    <% end %>
  </div>
</div>

app/views/incidencias/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Cargar Incidencias</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">

    <%= form_for(@incidencia, html: {class: 'form-horizontal', role: 'form', onsubmit: "$('.loading').show();"}) do |f| %>
      <div class="form-group">
        <%= f.label :tipo_incidencia, class: 'col-md-2 control-label' %>
        <div class="col-sm-3">
          <%= f.select :tipo_incidencia, options_for_select(Incidencia::TIPOS_INCIDENCIAS, selected: @incidencia.tipo_incidencia),
                                         {:include_blank => 'Seleccione Incidencia...'}, class: 'form-control', required: true, id: 'select_tipo_incidencia' %>
        </div>
      </div>

      <div class="form-group" id="div_select_cargos">
        <%= f.label :cargo_id, class: 'col-md-2 control-label' %>
        <div class="col-sm-3">
          <%= f.select :cargo_id, options_for_select(Cargo.all.collect {|cargo| [cargo.nombre, cargo.id]}, @incidencia.cargo_id),
                                     {:include_blank => 'Seleccione Cargo...'}, class: 'form-control', id: 'select_cargos' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :eleccion_id, class: 'col-md-2 control-label' %>
        <div class="col-sm-3">
          <%= f.select :eleccion_id, options_for_select(Eleccion.por_tipo(Eleccion::TIPOS[:paso]).collect {|el| [el.descripcion, el.id]}, selected: @incidencia.eleccion_id),
                                     {:include_blank => 'Seleccione Elección...'}, class: 'form-control', required: true %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag 'Datos Implicados', nil, class: 'col-md-2 control-label' %>
        <div class="col-sm-8">
          <div class='<%= "#{'field_with_errors' if @incidencias_invalidas.present? && !@incidencias_invalidas.empty?}" %>'>
            <%= text_area_tag 'datos', @incidencias_invalidas.try(:join, "\n"), rows: 10, class: "form-control", required: true %>
          </div>
          <p class="help-block">
            El formato para la carga de incidencias es el siguiente: <br>
            &nbsp;&nbsp;&nbsp;&nbsp;<b> NUMERO DOCUMENTO, TIPO DOCUMENTO [DNI, LC, ...],SEXO [M,F],DESCRIPCION INCIDENCIA</b> <br/>
            &nbsp;&nbsp;&nbsp;&nbsp; 123456789, DNI, M, DESCRIPCION INCIDENCIA <br/>
            &nbsp;&nbsp;&nbsp;&nbsp; 122377273, DNI, F, DESCRIPCION INCIDENCIA <br/>
          </p>

          <p class="help-block">
            El campo sexo es opcional pero se debe respetar la ubicacion y dejar el espacio vacio por ejemplo: <br>
            &nbsp;&nbsp;&nbsp;&nbsp; 122377273, DNI, , DESCRIPCION INCIDENCIA <br/>
          </p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= button_tag(type: "submit", class: "btn btn-primary") do %>
            Cargar incidencias
          <% end %>

          <%= link_to "Cancelar", :back, :class => "btn"%>
        </div>
      </div>
    <% end %>

  </div>
</div>

<script type="text/javascript">
  function showHideSelectCargos(show) {
    if(show) {
      $('div#div_select_cargos').show();
    } else {
      $('div#div_select_cargos').hide();
    }
  }
  $(document).ready(function() {
    showHideSelectCargos($("#select_tipo_incidencia").find("option:selected").val() === "REINCIDENCIA_CARGO");

    $("#select_tipo_incidencia").on("change", function() {
      showHideSelectCargos($("#select_tipo_incidencia").find("option:selected").val() === "REINCIDENCIA_CARGO");
    });
  });
</script>