config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Siel::Application.routes.draw do
  patch 'casos_verificacion/:id/firmar', to: 'casos_verificacion#firmar'
  patch 'casos_verificacion/:id/no_firmar', to: 'casos_verificacion#no_firmar'
  patch 'casos_verificacion/:id/borrar_datos', to: 'casos_verificacion#borrar_datos'

  # resources :verificaciones_firmas do
  #   resources :casos_verificacion
  #   patch :actualizar, on: :collection
  # end

  resources :usuarios do
    get :fuerza, on: :member
    get :find_by_email, on: :collection
    put :blanqueo_clave, on: :member
  end

  get 'usuario/cambiar_contrasenia', to: 'usuarios#cambiar_contrasenia'
  post 'usuario/cambiar_contrasenia', to: 'usuarios#cambiar_contrasenia'

  resources :archivos

  get 'archivos/descargar/:id', to: 'archivos#descargar'

  resources :renglones_padron
  resources :archivo_personas
  resources :archivo_lista_cargos
  resources :cargos

  resources :afiliaciones do
    delete :borrar_afiliaciones, on: :collection
  end

  resources :fiscales do
    delete :destroy_new, on: :member
    delete :borrar_fiscales, on: :collection
    post   :importar_fiscales, on: :collection
    get    :archivo_errores, on: :collection
    get    :exportar, on: :collection
    get    :establecimientos_por_comuna, on: :collection
    get    :cantidad_mesas_establecimiento, on: :collection
  end

  resources :personas do
    get :candidaturas, on: :member
    get :archivos_persona, on: :member
    get :busqueda_persona, on: :collection
    get :busqueda_persona_fiscal, on: :collection
    get :limpiar_formulario, on: :collection
    put :cargar_avatar, on: :collection
    get :ver_adjuntos, on: :member
    get :calcular_comuna, on: :collection
  end

  resources :mesa_extranjeros do
    post :importar_mesas_extranjeros, on: :collection
  end

  resources :importacion_escrutinios, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :calcular_resultados
      get  :reparto_cargos
      post :generar_lista_eleccion_general
      get  :imprimir_reparto_cargos
    end

    collection do
      get :estado_importacion_archivo
    end
  end

  # TODO: ver si hay que borrar, los documento se suben por el controller ArchivoPersonas
  post 'personas/adjuntar_documento', to: 'personas#adjuntar_documento'
  get 'personas/descargar_documento/:archivo_persona_id', to: 'personas#descargar_documento'

  resources :padrones do
    get :renglones_importados, on: :member
  end
  get 'padrones/importar/:index', to: 'padrones#importar'

  resources :candidaturas do
    post :renunciar, on: :member
    get  :cumple_ley_cupos, on: :member
    get  :cumple_minimo, on: :member
    get  :eventos, on: :collection
    post :sugerir_orden, on: :collection
    post :aceptar_correccion_cupo, on: :collection
    post :buscar_por_documento, on: :collection
    put  :aplicar_validaciones, on: :collection
    post :cambiar_orden, on: :collection
  end
  get 'candidaturas/importar/lista', to: 'candidaturas#importar_lista'
  post 'candidaturas/procesar_archivo', to: 'candidaturas#procesar_archivo'
  post 'candidaturas/auto_ordenamiento', to: 'candidaturas#auto_ordenamiento'
  post 'candidaturas/deshacer_ordenamiento', to: 'candidaturas#deshacer_ordenamiento'
  post 'candidaturas/subir', to: 'candidaturas#subir'
  post 'candidaturas/bajar', to: 'candidaturas#bajar'
  post 'candidaturas/filtrar'
  post 'candidaturas/oficializar_lista'
  post 'candidaturas/desoficializar_lista'

  get 'expedientes/buscar'

  resources :fuerzas do
    resources :infracciones
    get    :candidaturas, on: :member
    get    :apoderados, on: :member
    get    :agregar_apoderado, on: :collection
    post   :listado_apoderados, on: :collection
    get    :select_fuerzas, on: :collection
    patch  :editar_escudo
    delete :eliminar_escudo

    member do
      delete :baja
    end
  end

  resources :fuerza_eleccion, only: [:update]

  post 'fuerzas/filtrar'

  resources :elecciones do
    get 'descargar_resolucion'
    get :fuerzas, on: :member
    get :cargos, on: :member
    get :exportar_apoderados, on: :member
    get :actual, on: :collection

    post   :cargar_reparto, on: :member
    post   :grabar_reparto, on: :member
    delete :destroy_reparto, on: :member
    get    :reparto_anexo_1, on: :member
    get    :reparto_anexo_2, on: :member
    get    :reparto_anexo_2_2009, on: :member
    get    :reparto_anexo_3_2009, on: :member
    get    :reparto_anexo_4_2009, on: :member
    get    :reparto_anexo_5_2009, on: :member
  end
  post 'elecciones/filtrar'

  resources :eleccion_cargos
  resources :incidencias do
    delete :borrar_incidencias, on: :collection
  end

  resources :listas do
    resources :lista_cargos do
      member do
        post :borrar_candidaturas
        post :borrar_adhesiones
        post :importar_personas
        get  :estado_importacion_archivo
        get  :descargar_archivo_errores_importacion
        post :validar
        post :cerrar_lista
        post :abrir_lista
        get  :imprimir_candidaturas
        get  :exportar_adhesiones
        get  :descargar_exportacion_adhesiones
        get  :imprimir_auto_ordenamiento
        get  :versiones
        get  :exportar_versiones
        get  :descargar_exportacion_versiones
        get  :observaciones
      end
    end

    member do
      post :validar
      post :oficializar
      post :desoficializar
      get  :imprimir_lista_prototipo
      get  :imprimir_acta_presentacion
      get  :bitacora
      put  :asignar_numero_escrutinio
    end

    collection do
      get :seccion_cargos_habilitados
      get :imprimir_resolucion_oficializacion
      get :imprimir_comunicado_articulo_26
    end
  end

  resources :listas_generales do
    resources :lista_cargos_generales do
      member do
        get  :imprimir_lista_general
      end
    end
  end

  resources :observaciones, only: [:index, :edit, :update] do
    collection do
      post :subsanar
    end
  end

  resources :adhesiones, only: [:index, :create, :destroy]
  resources :configuraciones, only: [:show, :update]
  resources :siel_archivos
  resources :registro_candidaturas do
    delete :borrar_registros_candidaturas, on: :collection
  end

  resources :calles, only: [:index]

  resources :antecedentes_penales do
    member do
      post :enviar_solicitud
      get :descargar_antecedente_penal_pdf
    end
  end

  root to: 'root#index'

  # Rutas del controller admin
  post 'admin/login'
  post 'admin/login_extranet'
  get  'admin/login'
  get  'admin/logout'

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/elecciones_controller.rb
require 'reparto_d_hondt'
require 'reparto_error'

require 'reparto_anexo_1_pdf'
require 'reparto_anexo_2_pdf'
require 'reparto_anexo_2_2009_pdf'
require 'reparto_anexo_3_2009_pdf'
require 'reparto_anexo_4_2009_pdf'
require 'reparto_anexo_5_2009_pdf'

class EleccionesController < ApplicationController
  load_and_authorize_resource

  # GET /elecciones
  # GET /elecciones.json
  def index
    @anios = [''] + Eleccion.select(:fecha).map { |e| e.fecha.year }.uniq
    @elecciones = Eleccion.order('fecha DESC, descripcion ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elecciones }
    end
  end

  # GET /elecciones/actual.json
  def actual
    eleccion = Eleccion.actual

    respond_to do |format|
      format.json { render json: eleccion }
    end
  end

  # GET /elecciones/1/cargos
  def cargos
    eleccion = Eleccion.find(params[:id])

    respond_to do |format|
      format.json { render json: eleccion.cargos_seleccionados }
    end
  end

  # GET /elecciones/1/fuerzas
  def fuerzas
    @actual = Eleccion.find(params[:id]).general
    @fuerzas = @actual.fuerzas unless @actual.nil?
    @elecciones = Eleccion.por_tipo('general').order('fecha DESC')
  end

  # GET /elecciones/1/exportar_apoderados
  def exportar_apoderados
    actual = Eleccion.find(params[:id])
    @fuerzas = actual.fuerzas unless actual.nil?

    respond_to do |format|
      format.xls
    end
  end

  def filtrar
    anio = params[:anio].to_i
    @elecciones = anio != 0 ? Eleccion.where(fecha: Date.new(anio, 01, 01)..Date.new(anio, 12, 31)).order('fecha DESC, descripcion ASC') : Eleccion.order('fecha DESC, descripcion ASC')
  end

  def descargar_resolucion
    archivo = Eleccion.find(params[:eleccion_id]).archivo

    send_data archivo.contenido, filename: archivo.nombre, type: archivo.tipo_contenido
  end

  # GET /elecciones/1
  # GET /elecciones/1.json
  def show
    @eleccion = Eleccion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @eleccion }
    end
  end

  # GET /elecciones/new
  # GET /elecciones/new.json
  def new
    @eleccion = Eleccion.new

    # La primera vez hay que vincular la elección a los cargos
    @eleccion.asignar_cargos(Cargo.all)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @eleccion }
    end
  end

  # GET /elecciones/1/edit
  def edit
    @eleccion = Eleccion.find(params[:id])
  end

  # POST /elecciones
  # POST /elecciones.json
  def create
    @eleccion = Eleccion.new(parametros_permitidos)
    
    @eleccion.adjuntar_archivo(params[:archivo]) if params[:archivo].present?

    respond_to do |format|
      if @eleccion.save
        format.html { redirect_to elecciones_path, notice: I18n.t('messages.saved') }
        format.json { render json: @eleccion, status: :created, location: @eleccion }
      else
        format.html { render action: 'new' }
        format.json { render json: @eleccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elecciones/1
  # PUT /elecciones/1.json
  def update
    @eleccion = Eleccion.find(params[:id])

    if params[:archivo].present?
      @eleccion.archivo.destroy if @eleccion.archivo.present?
      @eleccion.adjuntar_archivo(params[:archivo])
    end

    respond_to do |format|
      if @eleccion.update_attributes(parametros_permitidos)
        format.html { redirect_to elecciones_path, notice: I18n.t('messages.saved') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @eleccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elecciones/1
  # DELETE /elecciones/1.json
  def destroy
    @eleccion = Eleccion.find(params[:id])
    @eleccion.destroy

    respond_to do |format|
      format.html { redirect_to elecciones_url }
      format.json { head :no_content }
    end
  end

  # GET /elecciones/repartos
  def repartos
    @elecciones_sin_resultados = Eleccion.all
    @elecciones = Eleccion.con_resultados

    @elecciones_sin_resultados -= @elecciones
  end

  # POST /elecciones/1/cargar_reparto
  def cargar_reparto
    @eleccion = Eleccion.find(params[:id])
    @eleccion.inicializar_resultados if @eleccion.resultados_elecciones.empty?

    preparar_variables_carga(@eleccion)

    # Ir guardando lo escrito al cambiar de tab
    @eleccion.assign_attributes(params[:eleccion]) if params[:eleccion]
  end

  # POST /elecciones/1/grabar_reparto
  def grabar_reparto
    @eleccion = Eleccion.find(params[:id])

    if @eleccion.update_attributes(params[:eleccion])
      if @eleccion.resultados_completos?
        begin
          # Asignar escanios y grabar el resultado en el mismo momento
          @eleccion.eleccion_cargos.each(&:desasignar_escanios)
          @eleccion.asignar_escanios.each(&:save)
        rescue Exception => e
          @eleccion.errors.add :base, e.message

          preparar_variables_carga(@eleccion)

          render action: 'cargar_reparto'
        end
      end
      redirect_to :repartos_elecciones
    else
      preparar_variables_carga(@eleccion)

      render action: 'cargar_reparto'
    end
  end

  # GET /elecciones/1/reparto_anexo_1.pdf
  def reparto_anexo_1
    eleccion = Eleccion.find(params[:id])
    comunas = Comuna.all

    respond_to do |format|
      format.pdf do
        send_data RepartoAnexo1Pdf.new(eleccion, comunas).render, filename: "eleccion_#{eleccion.fecha}_anexo_I.pdf", type: 'application/pdf'
      end
    end
  end

  # GET /elecciones/1/reparto_anexo_2.pdf
  def reparto_anexo_2
    @eleccion = Eleccion.find(params[:id])

    respond_to do |format|
      format.pdf do
        send_data RepartoAnexo2Pdf.new(@eleccion).render, filename: "eleccion_#{@eleccion.fecha}_anexo_II.pdf", type: 'application/pdf'
      end
    end
  end

  # GET /elecciones/1/reparto_anexo_2_2009.pdf
  def reparto_anexo_2_2009
    eleccion = Eleccion.find(params[:id])
    comunas = Comuna.all

    respond_to do |format|
      format.pdf do
        send_data RepartoAnexo22009Pdf.new(eleccion, comunas).render, filename: "eleccion_#{eleccion.fecha}_anexo_II.pdf", type: 'application/pdf'
      end
    end
  end

  # GET /elecciones/1/reparto_anexo_3_2009.pdf
  def reparto_anexo_3_2009
    eleccion = Eleccion.find(params[:id])

    respond_to do |format|
      format.pdf do
        send_data RepartoAnexo32009Pdf.new(eleccion).render, filename: "eleccion_#{eleccion.fecha}_anexo_III.pdf", type: 'application/pdf'
      end
    end
  end

  # GET /elecciones/1/reparto_anexo_4_2009.pdf
  def reparto_anexo_4_2009
    eleccion = Eleccion.find(params[:id])

    respond_to do |format|
      format.pdf do
        send_data RepartoAnexo42009Pdf.new(eleccion).render, filename: "eleccion_#{eleccion.fecha}_anexo_IV.pdf", type: 'application/pdf'
      end
    end
  end

  # GET /elecciones/1/reparto_anexo_5_2009.pdf
  def reparto_anexo_5_2009
    eleccion = Eleccion.find(params[:id])

    respond_to do |format|
      format.pdf do
        send_data RepartoAnexo52009Pdf.new(eleccion).render, filename: "eleccion_#{eleccion.fecha}_anexo_V.pdf", type: 'application/pdf'
      end
    end
  end

  # DELETE /elecciones/1/destroy_reparto
  # DELETE /elecciones/1/destroy_reparto.json
  def destroy_reparto
    @eleccion = Eleccion.find(params[:id])
    @eleccion.borrar_reparto

    respond_to do |format|
      format.html { redirect_to :repartos_elecciones }
      format.json { head :no_content }
    end
  end

  private

  def preparar_variables_carga(eleccion)
    @comunas = Comuna.all
    @comuna = (params[:comuna] ? @comunas.select { |c| c.id == params[:comuna].to_i } : @comunas).first
    @eleccion_cargos = eleccion.eleccion_cargos.select(&:seleccionado?)
    @fuerzas = eleccion.fuerzas.sort { |f1, f2| f1.numero <=> f2.numero }
    @resultados_comuna = eleccion.resultados_elecciones.select { |r| r.comuna == @comuna && !r.fuerza.nil? }
    @blancos_nulos = eleccion.resultados_elecciones.select { |r| r.comuna == @comuna && r.fuerza.nil? }
    @otros_resultados = eleccion.resultados_elecciones - @resultados_comuna - @blancos_nulos
    @resultados_comunas = @eleccion.resultados_comunas
  end

  def parametros_permitidos
    params.require(:eleccion).permit(:descripcion, :'fecha', :'fecha_posesion', :expediente, :notas,
                                     :observaciones, :fecha_limite_carga_candidaturas, :habilitar_carga_candidaturas,
                                     eleccion_cargos_attributes: [:id, :cargo_id, :seleccionado])
  end

end

app/helpers/elecciones_helper.rb
module EleccionesHelper

  def descripcion_resultado(resultado)
    if resultado.nulos?
      I18n.t('votos_nulos')
    else
      I18n.t('votos_en_blanco')
    end
  end

  def descripcion_reparto(eleccion)
    if eleccion.resultados_completos?
      eleccion.descripcion
    else
      "<i class='icon-warning-sign' title='#{I18n.t('messages.eleccion_sin_resultados_completos')}'></i> #{eleccion.descripcion}".html_safe
    end
  end

  def css_tr_reparto(eleccion)
    eleccion.resultados_completos? ? '' : 'warning'
  end

  def tab_css(comuna1, comuna2)
    (comuna1.nil? && comuna2.nil? || !comuna1.nil? && !comuna2.nil? && comuna1.id == comuna2.id) ? "class='active'".html_safe : ''
  end

  def tab_label(comuna, comuna_seleccionada)
    (!comuna_seleccionada.nil? && comuna.id == comuna_seleccionada.id) ? "Comuna #{comuna.numero}" : comuna.numero
  end

end

app/views/elecciones/_eleccion.html.erb
<tr <%= (eleccion.vigente?)? '': "class=warning" %>>
  <td><%= eleccion.fecha.year %></td>
  <td><%= eleccion.descripcion %></td>
  <td><%= eleccion.tipo %></td>
  <td><%= eleccion.cargos_seleccionados_concatenados %></td>
  <td nowrap>
    <%= eleccion.link_nombres_archivos_expedientes %>
  </td>
  <td>
  <%= link_to("<i class='glyphicon glyphicon-download'></i> #{eleccion.archivo.nombre}".html_safe, eleccion_descargar_resolucion_path(eleccion), class: "btn btn-default") if eleccion.tiene_resolucion? %>
  </td>
  <td><%= eleccion.eleccion_vigente %></td>
  <td style="text-align: right;">
    <%= link_to "<i class='glyphicon glyphicon-pencil'></i> Detalle".html_safe, edit_eleccion_path(eleccion), class: 'btn btn-default' %>
  </td>
</tr>

app/views/elecciones/cargar_reparto.html.erb
<div class="row">
  <div class="col-md-12">
    <%= titulo_con_linea "Reparto de Cargos para las elecciones '#{@eleccion.descripcion}'" %>
  </div>
</div>
<%= form_for(@eleccion, url: grabar_reparto_eleccion_path(@eleccion), method: :post, html: {class: '', id: 'form_resultados'}) do |f| %>

  <%= render "shared/error_messages", :target => @eleccion %>

  <div class="row well">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :porcentaje_exclusion, 'Umbral (%)', class: 'col-xs-3 control-label' %>
        <div class="controls col-xs-5">
          <%= f.text_field :porcentaje_exclusion, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">

        <ul class="nav nav-tabs">
          <% @comunas.each do |comuna| %>
            <li <%= tab_css(comuna, @comuna) %>>
              <%= link_to tab_label(comuna, @comuna), '#', onclick: "change_tab_comuna('#{cargar_reparto_eleccion_path(@eleccion)}', #{comuna.id});" %>
            </li>
          <% end %>
          <li <%= tab_css(nil, @comuna) %>>
            <%= link_to 'Distrito Único', '#', onclick: "change_tab_comuna('#{cargar_reparto_eleccion_path(@eleccion)}', null);" %>
          </li>
        </ul>
        <%= hidden_field_tag :comuna, (@comuna.nil? ? nil : @comuna.id), id: 'comuna_id' %>

      </div>
    </div>
    <div class="row">
      <div class="col-md-3">&nbsp;</div>
      <%= f.fields_for :resultados_comunas, @resultados_comunas do |frc| %>
        <% if frc.object.comuna == @comuna %>
          <div class="col-md-3">
            <div class="form-group">
            <%= frc.label :cantidad_mesas, 'Cantidad de Mesas', class: 'control-label' %>
            <div class="controls"><%= frc.text_field :cantidad_mesas, class: 'form-control' %></div>
          </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
            <%= frc.label :cantidad_inscriptos, 'Cantidad de Inscriptos', class: 'control-label' %>
            <div class="controls"><%= frc.text_field :cantidad_inscriptos, class: 'form-control' %></div>
          </div>
        </div>
        <% else %>
          <%= frc.hidden_field :cantidad_mesas %>
        <% end %>
      <% end %>
      <div class="col-md-3">&nbsp;</div>
    </div>
    <div class="row">
      <div class="col-md-12">

      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th colspan="2">Partido o Alianza</th>
            <%= f.fields_for :eleccion_cargos, @eleccion_cargos do |fec| %>
              <th width="20%">
                <%= fec.object.cargo.nombre %><br/>
                (cant. esca&ntilde;os <%= fec.text_field :cantidad_escanios, class: 'form-control' %>)
              </th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @fuerzas.each do |fuerza| %>
                <tr>
                  <td><%= fuerza.numero %></td>
                  <td><%= fuerza.nombre %></td>
                  <% @eleccion_cargos.each do |ec| %>
                    <%= f.fields_for :resultados_elecciones, @resultados_comuna.select { |r| r.fuerza_id == fuerza.id } do |fre| %>
                      <td><%= fre.text_field :cantidad_votos, class: 'form-control' %></td>
                    <% end %>
                  <% end %>
                </tr>
          <% end %>

          <%= f.fields_for :resultados_elecciones, @blancos_nulos do |fnulos| %>
            <tr>
              <td>&nbsp;</td>
              <td><%= descripcion_resultado(fnulos.object) %></td>
              <td><%= fnulos.text_field :cantidad_votos, class: 'form-control' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= f.fields_for :resultados_elecciones, @otros_resultados do |fre| %>
        <%= fre.hidden_field :cantidad_votos, class: 'form-control' %>
      <% end %>

    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12 well">
    <%= boton 'arrow-left', 'Volver al Listado', repartos_elecciones_path, '' %>
    <%= boton 'ok', 'Grabar', '#', 'btn btn-primary', id: 'link_grabar_resultados' %>
  </div>
</div>

app/views/elecciones/edit.html.erb
	<h2>Editando Elecci&oacute;n</h2>
	<hr/>

	<%= render 'form' %>

app/views/elecciones/filtrar.js.erb
	<%= render_filtro('body_table_elecciones', EleccionDecorator.decorate_collection(@elecciones)) %>

app/views/elecciones/fuerzas.html.erb
<div class="row">
	<div class="col-xs-12">
		<h3>Partidos / Alianzas Electorales</h3>
		<hr/>
	</div>
</div>

<%= form_tag({action: :fuerzas}, {class: 'form-inline'}) do %>
	<div class="row well">
		<div class="col-xs-6">
			<label>Elecci&oacute;n</label>
			<%= select_tag :id, options_from_collection_for_select(@elecciones, :id, :descripcion, params[:id]), id: 'eleccion_id', class: 'form-control' %>
			<%= link_to "<i class='glyphicon glyphicon-filter'></i> Filtrar".html_safe, '#', class: 'btn btn-default', id: 'link_filtrar_fuerzas' %>
		</div>
		<div class="col-xs-6 text-right">
					<em>Cantidad de partidos / alianzas encontrados: <strong class="cantidad_partidos"><%= @fuerzas.size %></strong></em>
		</div>
	</div>
<% end %>

<div class="row">
	<div class="col-xs-12">

		<table class="table table-striped table-hover">
				<caption>
						<i class='glyphicon glyphicon-flag'></i> - El partido es miembro de una alianza
				</caption>
				<thead>
					<tr>
						<th width="1%">N&uacute;mero</th>
						<th width="1%" nowrap># Expediente</th>
						<th>Nombre</th>
						<th>Expediente Digitalizado</th>
						<th>Estado</th>
						<th>Tipo</th>
						<th width="1%">&nbsp;</th>
					</tr>
				</thead>

				<tbody id="body_table_fuerzas">
					<%= render partial: 'fuerzas/fuerza_eleccion', collection: @fuerzas, as: :fuerza %>
				</tbody>

				<tfoot>
					<tr class="well">
						<td>&nbsp;</td>
					<td colspan="2">
								<em>Cantidad de partidos / alianzas encontrados: <strong class="cantidad_partidos"><%= @fuerzas.size %></strong></em>
					</div>
						<td colspan="4" style="text-align: right">
						<%= link_to "<i class='glyphicon glyphicon-list-alt'></i> Descargar Excel Apoderados".html_safe, "#{exportar_apoderados_eleccion_path(params[:id])}.xls", class: 'btn btn-success', target: '_blank' %>
							<%= link_to "<i class='glyphicon glyphicon-plus'></i> Nuevo".html_safe, new_fuerza_path, class: 'btn btn-success' %>
						</td>
					</tr>
				</tfoot>
		</table>

	</div>
</div>

app/views/elecciones/new.html.erb
<div class="page-header">
  <h2>Nueva Elecci&oacute;n</h2>
</div>

<%= render "form" %>

app/views/elecciones/repartos.html.erb
<div class="row">
	<div class="col-xs-12">
		<%= titulo_con_linea 'Reparto de Cargos' %>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">

		<table class="table table-hover table-striped">
			<thead>
				<tr>
					<th>Elecci&oacute;n</th>
					<th>Total de Mesas</th>
					<th>Total de Inscriptos</th>
					<th width="1%">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<% @elecciones.each do |e| %>
					<tr class="<%= css_tr_reparto(e) %>">
						<td><%= descripcion_reparto(e) %></td>
						<td><%= e.cantidad_mesas %></td>
						<td><%= e.cantidad_inscriptos %></td>
						<td nowrap>
							<%= boton('pencil', 'Editar', cargar_reparto_eleccion_path(e), '', method: :post) %>
							<%= boton('list', 'Ver Resultados', eleccion_cargo_path(e.primer_eleccion_cargo), 'btn-primary') %>
							<%= boton('remove', 'Borrar', destroy_reparto_eleccion_path(e), 'btn-danger', method: :delete, data: { confirm: '¿Está seguro que desea borrar el reparto cargado para esta elección?' } ) %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>
<div class="row">
	<div class="col-xs-12 well right">
		<%= boton('plus', 'Nuevo Reparto', '#', 'btn btn-success', id: 'link_nuevo_reparto') %>
		para las elecciones
		<div class="col-xs-2 pull-right">
			<%= select_tag :eleccion, options_from_collection_for_select(@elecciones_sin_resultados, :id, :descripcion), class: 'form-control' %>
		</div>
	</div>
</div>

<%= form_tag({}, {id: 'form_nuevo_reparto'}) do |f| %>
<% end %>

app/views/elecciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descripcion:</b>
  <%= @eleccion.descripcion %>
</p>

<p>
  <b>Fecha:</b>
  <%= @eleccion.fecha %>
</p>

<p>
  <b>Notas:</b>
  <%= @eleccion.notas %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @eleccion.observaciones %>
</p>


<%= link_to 'Edit', edit_eleccion_path(@eleccion) %> |
<%= link_to 'Back', elecciones_path %>